club-1/docs

conf.py
disable smartquotes at sphinx level to enable it at MyST level.
=> fix: smart quotes sometimes doubled with md emphasis

Makefile, conf.py
- rename LANGUAGE exported env var to LOCAL, not to disturb Make messages
- remove failing sphinx commands
- remove quotes around BUILDDIR and SOURCEDIR as these will never have spaces
- share doctrees for localized builders for perf. This also fixes warning for epub
about .doctrees unknown mimetype
- fix LaTeX paper size to always use A4
- fix today format to use a localized version
=> build: small fixes & enhancements

Makefile, _templates/index.html
It based on nginx's one, with the meta viewport added, as it is not there by default
(see https://mailman.nginx.org/pipermail/nginx-devel/2020-November/013609.html)
It could be customized later.
=> feat: add very basic index template

services/email.md
Notamment le fait qu'il est désormais possible d'utiliser les adresses `imap.club1.fr` et `smtp.club1.fr` en plus de l'officielle `mail.club1.fr`.
C'est pratique parce que c'est visiblement les adresses que choisissent la plupart des clients emails testé jusqu'ici (geary, gmail android, k9-mail, etc.).
=> docs: ajout d'informations concernant les emails

interne/meta-doc.md
Qui conseille de souvent faire des retours à la ligne
=> docs: ajout d'une astuce Git dans la meta-doc

_templates/club1.sty, conf.py, interne/meta-doc.md
- Emojis (en déclarant NotoColorEmoji comme police de fallback. See https://tex.stackexchange.com/a/572220)
- Couleurs des blocs
- Meilleur middot
- Pagerefs
**avant**
**après** (emojis, couleurs, pagerefs)
**avant**
**après** (couleurs)
**avant**
**après** (emojis, middot)
=> pdf: customizations including emojis and admonition colors

.github/workflows/build.yml, .github/workflows/deploy.yml, Makefile, _templates/index.html, _templates/versions.html, conf.py, interne/meta-doc.md
- [PDF](https://public.club1.fr/nicolas/club1.pdf)
- [EPUB](https://public.club1.fr/nicolas/club1.epub)
- Targets make permettant de build tout d'un coup (site + PDF + EPUB): `make all` ou bien `make all/fr` par exemple (a693706, 0577d5f).
- Ajout des versions PDF et EPUB au menu de version sur le site (a693706).
- Ajouts de détails concernant le build du PDF dans la doc (1e2ee45).
- Peaufinage des customisation LaTeX et du script de compilation (0293b75, f36befc).
- Séparation du build automatique GitHub en 2 workflows, dont un qui build tout avec `make all` (6417cfd).
- Suppression du dernier SVG inclus dans la doc, car LaTeX ne pouvait pas les gérer, ce qui nécessitait un plugin Sphinx et ImageMagick (0e10bc3).
- Correction de l'action de déploiement GitHub en ajoutant les paquets de …
=> Compilation et publication des versions PDF et EPUB également

.github/workflows/deploy.yml, _templates/club1.sty, interne/meta-doc.md
NotoColorEmoji embeds png into OTF fonts so the resluting PDF is not fully vectorial and the emojis connot be selected.
Twemoji is included in TeX Live so it can be easily included in the document.
See the resulting PDF (for instance page 2): https://public.club1.fr/nicolas/club1.pdf
=> pdf: use Twemoji font to allow selection and vectorial rendering

Makefile, _templates/club1.sty, _templates/style.xdy, tutos/connexion-linux.md, tutos/mes-premiers-pas-sur-le-web.md, tutos/webdav-android.md
- use 3 column layout for index and fill lines with aligned dots.
- use alpha numbering for title page
**before**
**after**
=> pdf: index customizations + page numbering

_templates/club1.sty, conf.py, docutils.conf, info/general.md, interne/meta-doc.md, services/ssh.md, services/webdav.md
<details>
<summary>pdf: customisation des tableaux 2b20212f64426e1528e7cf7c1bdc126098b98ecc</summary>
**avant**
**après**
</details>
<details>
<summary>docs: utilisation de glossaire pour les définition des services + petites modifications dans le texte 1f6c4467abafa1020325568e93732d3d94ee1ab1</summary>
**avant**
**après**
</details>
<details>
<summary>pdf: corrections des warnings LaTeX b885c2f68834a287f03e1d3b9acfdb36eb208d0e</summary>
- Spécification manuelle de la variante SmallCaps de lmodern car fontspec n'arrivait pas à la trouver. Corrige les warnings de ce type :
```
LaTeX Font Warning: Font shape `TU/LatinModernRoman(0)/m/sc' undefined
(Font)              using `TU/LatinModernRoman(0)/m/n' instead on input line 1128.
```
- Correction du thème Bjornstrup, qui produisait des …
=> Pagaille bis

_locales/en/LC_MESSAGES/package.po, _locales/package.pot, _templates/club1.sty, conf.py, interne/meta-doc.md
Ajoute le bloc de métadonnées suivant à la doc (PDF et HTML) :
=> docs(meta): versions utilisées lors de la compilation

_ext/french_typography.py, _ext/term_tooltips.py, conf.py
added as a PostTransform.
Closes #100
=> build: first add of term ref titles (tooltips)

_ext/index_role.py, _locales/exclude.po, _static/club1.css, conf.py, services/email.md, services/webdav.md, tutos/webdav-android.md
Ce rôle permet d'ajouter dans l'index un lien vers un (groupe de) mot(s) d'une page.
Il est à utiliser pour des termes auxquels on fait référence plusieurs fois à travers la docs, mais qui n'ont pas besoin d'être définis.
Comme ici, pour les "calendriers" et "carnets d'adresses".
Le but est de permettre au lecteur de rapidement trouver tous les endroits où un concept est utilisé.
Il seront affichés dans l'index d'une manière différente des définitions.
Pour améliorer l'expérience utilisateur, le terme référencé est mis en lumière lorsqu'on clique sur le lien depuis l'index. Pour cela, le CSS est légèrement modifié et une extension sphinx ajuste le fonctionnement du rôle "index".
Au passage, une liste de définition est passée sous la forme de glossaire dans la page WebDAV.
=> docs: première utilisation du rôle "index"

info/general.md
Il est présent aussi dans les URLs automatiques.
À merger en mode `squash and merge`.
=> docs: correction détails identifiant des membres

.github/workflows/build.yml, _templates/club1.sty
=> pdf: augmente la pénalité de pagebreak juste avant un bloc

.github/requirements.txt, .github/workflows/build.yml, .github/workflows/deploy.yml, 404.md, _locales/en/LC_MESSAGES/package.po, _locales/exclude.po, _locales/package.pot, conf.py, interne/meta-doc.md
il y faudra modifier la configuration du virtualhost pour y ajouter ce bloc :
```apache
<LocationMatch "^/docs/(?<LANG>[a-z]{2})/">
ErrorDocument 404 "/docs/%{env:MATCH_LANG}/404.html"
</LocationMatch>
```
=> html: add custom 404 error page

glossaire.md, interne/meta-doc.md, services/web.md
Apache était référencé à deux endroits de la doc. C'est le moment d'ajouter une entrée de glossaire.
=> docs: ajout de la définition de Apache + refs termes

services/email.md
2 logiciels supplémentaires sont utilisés pour le service email.
À merger en mode "squash".
=> Ajout de logiciels utilisés pour les emails

.markdownlint.json, glossaire.md, interne/aliases.md, services/email.md
J'ai essayé de rendre ça clair mais c'est pas évident.
C'est peut-être un peu fort de mettre ça en première sous-sections mais je trouvais que ça allait bien en dessous du premier paragraphe.
Le warning du lien vers les filtre sera résolu une fois que #150 sera mergé.
Fix #148
=> docs: infos à propos des sous-adresses

faq.md, index.md, services/email.md
La FAQ comprends un sommaire. Il sera particulièrement utile lorsqu'elle contiendra beaucoup de questions-réponses.
Le style de titre `settext` (souligné) n'a pas besoin d'être respecté dans cette page. En effet les titres sont des questions complètes ce qui les rends très longs. Il serait fastidieux de tous les souligner manuellement jusqu'au bout. Et un soulignement partiel rendrait les titres étranges.
Des détails ont été ajoutés par rapport à l'unique boite email. C'est le gros point bloquant du service email actuel (et ça le restera probablement longtemps).
Closes #134 
P.S. haha le sommaire a un drôle de style dans la version pdf !
-----------------------------
EDIT: Du coup j'ai désactivé cette boite ombrée dans https://github.com/club-1/docs/commit/b7d1bd2acd84d0f3acf9d198008164824 …
=> docs: premier ajout de la FAQ & précision email

cgu.md
Remplace une injonction à créer un ticket Github
par une invitation plus large à signaler le problème
ajout d'un lien vers la doc : demande et incident
=> retrait ticket Github CGU

services/git.md
Corrige aussi quelques erreurs au passage.
=> docs: définit sh comme langages des blocs git

glossaire.md
Directement dans le glossaire, vu que celui au début de la doc a été retiré dans #189
=> Ajout d'un avertissement par rapport à GitHub

_templates/club1.sty, tutos/caldav-mac.md, tutos/connexion-linux.md, tutos/flux-rss.md, tutos/presentation.md, tutos/webdav-android.md, tutos/webdav-mac.md
Et peaufinage de l'affichage des `guilabel` et `kbd` en latex.
& Corrections de mini fautes.
Sphinx a un role prévu exprès pour les boutons de GUI. Comme ça on a plus besoin de se demander si on doit les mettre **en gras**, "entre guillemets", ou `en code`. 
HTML:
PDF:
=> docs: utilisation de guilabel dans les tutos

_static/club1.css, _templates/layout.html, conf.py
Il reste juste un défaut : les pages lorsqu'elles sont chargées scrollent juste en dessous de la barre. C'est dû à un morceau de JavaScript du thème que je ne peux pas vraiment modifier simplement. C'est un peu dommage mais ça ira non ?
=> Intégration de la barre d'entête de CLUB1

conf.py, faq.md, services/ssh.md, tutos/premiere-connexion-ssh.md
Comme il est prévu d'ajouter à un moment une petite liste de commandes SSH à utiliser sur le serveur, il serait utile de facilement pouvoir les référencer.
On en a déjà un exemple avec la commande `passwd`.
Le rôle "manpages" est lui intégré à Sphinx. Il est configuré pour automatiquement créer un lien vers les pages de manuel de Debian. Je trouve le visionneur de page de manuel de Debian vraiment sympa car il a une mise en page assez moderne et responsive. Et aussi il prends en compte les différents languages dans lesquels sont des fois traduites ces pages.
Par exemple la page de la commande `passwd` en français (bon elle n'est pas entièrement traduite mais c'est mieux que rien) : https://manpages.debian.org/bullseye/passwd/passwd.1.fr.html
=> Ajout du rôle "commande" et configuration des manpages

services/email.md
Car il est installé sur le serveur.
=> docs: ajout de Mutt aux logiciels installés pour les emails

index.md, services-ouverts/index.md, services-ouverts/matrix.md, services/index.md
Depend de #228.
- docs: précision à propos des services réservés aux membres
- docs: ajout services ouverts et notice de Matrix
Pour l'instant c'est surtout une copie de la notice existante (mais un peu délaissée) sur le site, en partie Sphinxisée. Plus tard on pourra déplacer le dossier `services` (mais avec une redirection).
=> Ajout de la section "services ouverts", de la notice Matrix et quelques définitions

.github/workflows/build.yml, .github/workflows/deploy.yml, conf.py, outils/index.md, outils/ldap.md, outils/meta-doc.md
Un peu succin pour le moment. Mais mieux que rien.
- docs: premier ajout de LDAP (+ config de graphviz)
- docs: ajout de Graphviz à la liste des dépendances de la doc
Pour ce faire une petite idée de ce que donne le graphe décrit ici:
https://github.com/club-1/docs/blob/039e1836ae0ea6fcdfa80be28a42f243f448b116/outils/ldap.md?plain=1#L31-L43
=> Premier ajout de la page LDAP

faq.md
Voir: <https://forum.club1.fr/d/106>
=> docs: gandi ne propose plus d'emails fournis avec un nom de domaine

glossaire.md, info/espace-personnel.md, info/general.md, outils/meta-doc.md, services/web.md, tutos/mes-premiers-pas-sur-le-web.md
- déplacement des définitions dans le glossaire
- ré-organisation des chapitres pour une meilleure progression
- retrait des infos non-essentielles (ton article et pas doc)
- ajout au glossaire des termes "site statique" et "site dynamique"
- exemple de mail pour lier domaine voir <https://forum.club1.fr/d/111>
- exemple d'organisation des dossiers pour sites Web
=> remaniement de la section service/web

info/general.md
Suite à la migration de Ubuntu 20.04 à Debian 11.
=> docs: MAJ des versions et logiciel et du nom de distrib

.github/requirements.txt, _templates/club1.sty, conf.py, info/espace-personnel.md, info/general.md, info/infrastructure-materielle.md, info/politique-de-vie-privee.md, outils/aliases.md, outils/dns.md, outils/forum.md, outils/newsletter.md, services/email.md, services/web.md
- build: update Sphinx to unreleased 6.2 version
- latex: update code block styles after Sphinx update to 6.2
- latex: update table styles after Sphinx update to 6.2
- latex: make sphinxseealso styles match HTML theme
- latex: use \sphinxremovefinalcolon instead of mine
- latex: adjust styles of bloc quotes
- docs: utilisation de {seealso} existant dans Sphinx
Pour le moment ce n'est pas mergeable car Sphinx 6.2 n'est pas encore sortie.
Closes #208
=> Mise-à-jour vers Sphinx 6

services/ssh.md, tutos/premiere-connexion-ssh.md
+ ajoute une intro
Voir <https://forum.club1.fr/d/153>
=> Sélection de commandes dans service SSH

info/general.md, outils/index.md, outils/sauvegardes.md
Voir <https://forum.club1.fr/d/148-follow-up-de-la-migration-debian>
Finalement j'ai décidé de faire des gros blocs de code entrecoupés de titres. Ça permet de ne pas ajouter aux traductions la plupart du texte dans lequel il n'y avait de toute façon rien à traduire.
Ça rapproche aussi un peu plus d'une forme de script que l'on pourrait imaginer réaliser à terme.
[Prévisualisation](https://github.com/club-1/docs/blob/n-peugnet-sauvegardes/outils/sauvegardes.md)
=> Ajout du protocole de restauration des sauvegardes

tutos/premiere-connexion-ssh.md
L'emoji n'était pas très facile à voir en jaune sur gris.
Avant :
Après :
=> Utilisation d'un symbole NB au lieu d'un emoji

info/general.md, services/matrix.md
Offerts par le RésiLien, pour remplacer UptimeRobot
=> Nouvelle page de statut / outil de monitoring

_static/club1.css
Uniquement avec le builder html, pour le moment.
Comme proposé dans https://forum.club1.fr/d/157-affiner-la-section-servicessh
=> Nouveau style pour les définitions de commandes

_ext/term_tooltips.py, conf.py
By extending Sphinx's TextWriter and dependencies, we can handle the docutils nodes as we wish.
Now, the tables are displayed as clipped text with only their label as a caption, xref and term references are surrounded by square brackets, to see in advance if the definition contains references to other terms.
Some behaviour has been directly inherited from Sphinx's TextWriter, mainly the indentation for some blocks (e.g. the admonitions), the lists should now be displayed properly and the inline code literals are surrounded by straight double quotes.
*Before*:
*After*:
=> Handle markup in term tooltips

glossaire.md
Quelques fautes de français et uniformisation des acronymes anglais (simplement mis entre parenthèses et en emphase comme tous les autres).
=> Corrections et uniformisation du glossaire

services/web.md
Apache gère énormément de projets différents. Je pense que donner le nom complet peut permettre d'éviter des confusions.
=> Ajout du nom complet de Apache httpd

info/general.md
Comme on est déjà à 3 comptes contenant des chiffres (j'ai pas fait gaffe), autant les autoriser directement dans la doc.
=> Autorisation des chiffres dans l'identifiant

outils/compta.md
J'ai remarqué qu'il n'y avait pas de lien vers le repo Git des scripts de compta. Voici donc une proposition d'ajout pour palier à cela.
=> ajoute un lien vers la source pour les scripts de compta

conf.py
This endpoint seems to be severly limited by GitHub which slows down the linkcheck jobs by a large mount.
We don't really need to check this URL as we know it will exists as long as we use GitHub to share the docs sources.
=> Do not check our own github commits link

services/email.md
agrandissement de l'introduction et réorganisation des sections.
La plupart des ancres liés aux titres ont été conservées à part "détails divers" qui a été transformé en "usage avancé"
=> clarification service email

services/email.md
Finalement j'ai remis SPF-Engine car il log plus d'informations (utile pour le debug) et il permet une configuration plus poussée.
=> MAJ de la configuration SPF

services/ssh.md
ça parait tellement évident quand on a l'habitude, qu'on n'a même pas écrit qu'il fallait taper le nom de la commande avant d'appuyer sur Enter 😅.
=> améliore l'astuce pour lancer une commande via SSH
