club-1/docs

README.md, locales/en/LC_MESSAGES/package.po, locales/package.pot
- docs: add info about sphinx, markdown, git & gihub
- docs: move references below edition infos
=> Better meta-docs

locales/en/LC_MESSAGES/package.po, locales/package.pot, services/git.md, services/index.md
Closes https://github.com/club-1/hosting/issues/37
=> docs: add first git hosting page

_templates/layout.html, locales/en/LC_MESSAGES/sphinx.po, locales/sphinx.pot
=> feat: add link in sidebar to return to main site

locales/en/LC_MESSAGES/package.po, locales/package.pot, services/web.md
[diff](https://github.com/club-1/docs/compare/main..n-peugnet-web-static?short_path=4605f20#diff-4605f203dd7667f32e76e8af1cdcad9b72757b8b07e5385864f5475b0af62179) (cliquer sur la petite page pour voir le rendu)
=> docs: add info about static websites

Makefile, README.md, conf.py, general.md, glossary.md, index.md, locales/en/LC_MESSAGES/package.po, locales/package.pot, services/git.md
- feat: start using Sphinx specific features
- feat: use --previous flag of msgmerge for changes in weblate
- i18n: run update po
=> feat: use sphinx glossary and term refs

general.md, glossary.md, locales/en/LC_MESSAGES/package.po, locales/package.pot, services/email.md, services/index.md
had to recursively add a lot of terms to the glossary... XD
=> docs: add email service page

locales/en/LC_MESSAGES/package.po, locales/package.pot, services/drive.md, services/index.md, services/webdav.md
- docs: add webdav & drive
- i18n: update pot
=> Add webdav and drive

_static/club1.css, conf.py
- style: add dotted underline to glossary links
- style: better way to include additional css files
- style: better css rules + custom external links
=> Some styles updates

locales/en/LC_MESSAGES/package.po, locales/package.pot, tutos/webdav-android.md
- docs: corrections de maniaque
- i18n: run update-po
=> Corrections tuto webdav

_static/club1.css
had to fix some of the icon styles to make it look good
=> style: add underline to links on hover

locales/en/LC_MESSAGES/package.po, locales/package.pot
and fix some translations by the way
=> i18n: run update-po

services/ssh.md
- séparation de la partie "se connecter" en "avec mot de passe" et "avec une clé publique".
- plus de détails sur la partie des clés de chiffrement
=> Ajout de détails sur la partie SSH

services/webdav.md
- Mention du client web email pour consulter et modifier les calendriers et carnets d'adresse.
- Titre plus parlant
=> Petit paragraphe sur les contacts & calendriers

README.md
Quelques fautes et informations obsolètes
=> Légères corrections sur la meta-doc

info/espace-personnel.md
L'utilisation de l'indentation au lieu des ``` pour les code blocks permet d'éviter la détection intempestive de langage.
=> docs: quelques corrections sur la nouvelle page espage perso

interne/aliases.md
Peut-être pas très clair, mais au moins les infos sont à jour comme ça.
=> Mise à jour de la modification des alias email

conf.py
it was failing because of the emojis
=> fix pdflatex build by using xelatex

conf.py, tutos/webdav-android.md
Juste un draft pour le moment, histoire de voir ce que ça donne.
=> docs: use figures in android webdav tuto

_static/tutos/mes-premiers-pas-sur-le-web/bonjour.txt, conf.py, info/general.md, services/drive.md, tutos/connexion-linux.md, tutos/mes-premiers-pas-sur-le-web.md, tutos/webdav-android.md
Notamment le lien download dans le tuto web :
**HTML**
**PDF**
=> docs: quelques corrections par-ci par-là

tutos/connexion-linux.md, tutos/webdav-android.md
- passage des images à la syntaxe de figure
- quelques reformulations
- les figures sont cross-référençables, il leur faut donc un label unique
=> docs: modifs tuto explorateur de fichiers linux

_templates/club1.sty
- pdf: imite le style de quote de la version HTML 652d275dd2b8101cb8f83b2846fc80e2ab16fcba
**PDF avant**
**PDF après**
**HTML**
- pdf: imite le style d'admonition de la version HTML eeac8a19e434ff733baca355270a4cd9092e8f94
Closes #88
=> pdf: imite le style de quote et d'admontitions de la version HTML

.github/matchers/sphinx.json, .github/workflows/build.yml, .github/workflows/deploy.yml, .gitignore, Makefile
and use custom problemMatcher instead
=> ci: drop fragile sphinx-action

_ext/term_tooltips.py, conf.py
and filter everything after the emdash.
**avant**:
**après**:
=> build: add apply function to termtext

info/general.md
J'ai encore merdé dans les commit, mais le résultat dans les "files changed" est bon
Closes #103 
Closes #75
=> transfert infos site vers doc

_locales/exclude.po, conf.py, glossaire.md, services/ftp.md
- docs: ajout de quelques définitions
- build: more robust emdash strip
=> docs: définitions et minifix

glossaire.md
Définitions plus précises, ajout d'HTML, et corrections de fautes
=> docs: étoffage du glossaire

_locales/exclude.po, services/ssh.md
Closes #69
À merger en mode `Squash and merge`.
=> docs: ajout d'infos à propos de SFTP et SCP

.github/workflows/build.yml, .markdownlint.json, info/espace-personnel.md, info/general.md, interne/aliases.md, interne/meta-doc.md, services/rss.md, services/ssh.md, tutos/connexion-linux.md, tutos/flux-rss.md, tutos/webdav-android.md
Il est intéressant de reviewer commit par commit afin de voir d'abord les erreurs relevées puis les corrections appliquées.
GitHub n'affiche que les 10 premières erreurs dans les "fichiers changés". Mais ça devrait suffire la plupart du temps.
=> ci: lint md files using markdownlint

info/general.md
Fournisseurs de services et détails des sauvegardes
Part of #135
Closes #138
=> Ajout d'infos pour les CHATONS

_locales/exclude.po, glossaire.md, services/drive.md, services/email.md, services/ftp.md, services/git.md, services/rss.md, services/sql.md, services/ssh.md, services/web.md, services/webdav.md
ainsi qu'un lien vers leurs sources
=> docs: ajout des logiciels utilisés par les services

.github/requirements.txt, .github/workflows/build.yml, .github/workflows/deploy.yml, conf.py
- build: add optionnal 'last updated by git' ext
- update github workflow for 'last updated by git'
=> build: ajout de la date de dernière modif sur chaque page

services/email.md
Comme dit ici https://github.com/club-1/docs/pull/144#discussion_r956774210
=> .forward separateur retour à la ligne

services/email.md
Maintenant que https://github.com/club-1/hosting/issues/51 est fait, il faut le documenter un minimum.
=> docs: infos à propos des filtres Sieve

cgu.md, info/cgu.md, info/index.md
fix #143 
Voici un premier jet, basé sur l'exemple sur le Git CHATONS : https://framagit.org/chatons/CHATONS/-/blob/60a172b8c37b133107a268f396826c2a167182d2/docs/CGU_types.md
=> CGU : premier jet

faq.md, glossaire.md, info/espace-personnel.md, services/web.md
4 nouveaux mots au glossaire !
=> enrichissement du service/web

services/rss.md
Et ajout d'un lien vers Wikipedia.
=> Reliage des définitions RSS et agrégateur

interne/meta-doc.md
Utilisé lors de la compilation de la doc.
=> docs: ajout du logiciel Sphinx-last-updated-by-git

glossaire.md, info/general.md
ajout des méthodes email et matrix
avertissement concernant Github
=> MAJ demandes et incidents

services/sql.md
Part of https://github.com/club-1/hosting/issues/72
=> Mise à jour URL phpmyadmin

info/general.md, info/index.md, info/politique-de-vie-privee.md
C'est juste un petit début de ce qu'on a fait pendant le workshop pour lancer son écriture
=> Ajout politique de sécurité & engagements admin système

info/general.md
ferme https://forum.club1.fr/d/18
=> tickets : remplacement du lien Github par un lien vers le forum

info/espace-personnel.md, tutos/index.md, tutos/presentation.md
=> tutoriel : éditer sa présentation

info/general.md
Pour correspondre aux dernières modifs de la configuration.
=> docs: MAJ de la section sauvegardes

glossaire.md, services/email.md, services/ssh.md, services/web.md, tutos/index.md, tutos/premiere-connexion-ssh.md
- nouveau term : fichier/dossier cache
=> tuto premiere co ssh

tutos/premiere-connexion-ssh.md
Car il n'a toujours pas été réellement  testé sur Windows.
=> Avertissement windows tuto première co SSH

info/general.md
Peut-être un peu succin, mais au moins le lien est là.
Fixes: #135
=> Ajout d'un lien vers la page status.club1.fr

_templates/cgu.html, _templates/layout.html, cgu.md
- Allow to set template per page
- Ajout de la date de dernière modif en haut des CGU
=> Ajout de la date de dernière modif au début des CGU

glossaire.md, info/espace-personnel.md
- entrée de glossaire
- logiciel `logrotate`
- dossier `log` de l'espace perso
Ferme https://forum.club1.fr/d/49
=> docs: Ajout d'infos à propos des logs

glossaire.md, services/sql.md
- ~~docs: minuscules dans le glossaire pour les noms communs~~ &rarr; déplacé vers #213 
- docs: ajout de la définition d'instance
- docs: étoffage de la documentation SQL
Je peux déplacer les modifications du glossaire (premier commit) dans une autre PR au besoin.
Edit: bon je vais le faire là, ça sera plus compréhensible.
=> docs: Ajout de détails par rapport à SQL

services/rss.md
Utilisation des `{guilabel}` dans ce fichier.
=> docs: guilabel mini tuto API TTRSS

Makefile, _patches/theme-js-nav-no-reset.diff, _static/js/.gitignore
Pour cela, un dossier _patches a été ajouté. Il contiendra à l'avenir tous les patches à appliquer sur les différentes sources.
Override and closes #220
=> Désactive le scroll du nav en JS dans le theme HTML V2

.github/requirements.txt
=> MAJ Sphinx vers la version 5.3.0

_templates/packages.sty, conf.py, glossaire.md, info/espace-personnel.md, outils/meta-doc.md, services/drive.md, services/email.md, services/ftp.md, services/git.md, services/rss.md, services/sql.md, services/ssh.md, services/web.md, services/webdav.md, tutos/premiere-connexion-ssh.md
Avantage:
- les logiciels ont leur propre domaines et les termes peuvent donc être défini différemment en fonction de leur domaine.
- les termes ainsi définis ont des entrées d'index en mode paire
Inconvénients:
- dans le PDF, les références ajoutent une indication de page, qui est souvent redondante avec l'index.
=> entrées de logiciels utilisant les domaines Sphinx

services/web.md
Conformément à https://forum.club1.fr/d/70
=> docs: utilisation de l'alias webmaster@club1.fr

glossaire.md, info/politique-de-vie-privee.md, outils/aliases.md
Et déplacement de l'astuce de la commande `members`.
=> docs: ajout définition de "groupe" au glossaire

outils/forum.md, outils/index.md
https://forum.club1.fr/d/26-documenter-la-moderation-et-ladministration-du-forum
=> docs: premier ajout de la page d'outil "forum"

outils/forum.md
Ajoute un paragraphe concernant les deux méthodes de connexion
=> ajout : connexion au forum

services-membres.md, services/webcast.md
En mentionnant bien que la configuration actuelle est considérée comme une "beta".
Voir : https://forum.club1.fr/d/87-page-de-doc-pour-le-service-membre-de-web-radio
=> docs: ajout de la page du service de webdiffusion Icecast

info/general.md, services/matrix.md
See https://forum.club1.fr/d/90
=> Stop using the redirection URL for UptimeRobot links

tutos/premiere-connexion-ssh.md
Comme dit sur le forum https://forum.club1.fr/d/96
=> tuto: SSH: attention pour le mot de passe et astuce pour coller

info/general.md
Il y a déjà deux membres CLUB1 qui en ont 17, dont autant monter la barre.
=> Autorisation jusqu'à 17 caractères pour le nom d'utilisateur

glossaire.md, outils/aliases.md, services/git.md, services/ssh.md, tutos/mes-premiers-pas-sur-le-web.md, tutos/premiere-connexion-ssh.md, tutos/webdav-mac.md
Voir: https://forum.club1.fr/d/96
=> docs: placeholder: utilisation de maj au lieu de chevrons

_locales/exclude.po, outils/dns.md, outils/index.md
CC: @etienne-lelouet
Voir: https://forum.club1.fr/d/123
=> docs: premier ajout de la page outils/dns

info/general.md
- retire le regex
- ajoute des règles compréhenssibles par des humains
- écriture inclusive pour faire fuir les fachos
=> infos sur le nom d'utilisateur moins cryptiques

outils/index.md, outils/newsletter.md
Hop là !
Comme avec Nico on a fait quelques amélioration ainsi qu'une installation en bonne et due forme, j'en ai profité pour rapidement noter la configuration et en décrire l'usage.
=> ajout de la page newsletter dans les outils

faq.md
La phrase est pas ouf, mais j'avais pas d'inspi, l'important c'est surtout que le lien soit présent :)
=> docs: légères modifs FAQ (backlinks: none, astuce tuto SSH, typo)

outils/index.md, outils/ldap.md, outils/newsletter.md
- Meilleure description de nss-pam-ldapd
- Déplacement de la page aliases après la page forum
- Corrections multiples dans newsletter
=> docs: modifications éparses de la section outils

conf.py, glossaire.md, outils/index.md, outils/site.md, outils/wiki.md
Ajoute une page dans la section "outils" expliquant comment participer à l'édition du site Web de CLUB1.
+ ajoute le terme "Wiki"
+ ajoute le logiciel "W"
=> Edition du Wiki de CLUB1

tutos/premiere-connexion-ssh.md
Voir <https://forum.club1.fr/d/138>
=> Utilisation de Powsershell pour le tuto premiere co ssh

faq.md
Pour que ce soit plus clair que le tuto n'est pas que pour les débutants.
=> Reformulation de la FAQ modification du mot de passe

outils/dns.md
=> Mise à jour des infos du serveur DNS

_locales/exclude.po, glossaire.md, outils/site.md
Voir : https://fr.wiktionary.org/wiki/wiki
=> wiki est un nom commun

info/infrastructure-materielle.md
+ ajouts détails infra matériel
=> MAJ SSD système

services/webcast.md
=> Ajout du logiciel icecast-ldap

tutos/premiere-connexion-ssh.md
suite aux retours de Cosme :
https://forum.club1.fr/d/165
et de Lucie :
https://forum.club1.fr/d/96
Closes #266
=> remaniement du tuto ssh

faq.md
Nouvelle entrée dans la FAQ
https://forum.club1.fr/d/177
=> FAQ : espace occupé

services/ssh.md
Depend de sphinx-doc/sphinx#11825 puis de la MAJ de Sphinx vers la dernière version (#286).
=> Cible custom pour la manpage mailx vers bsd-mailx

_locales/exclude.po, glossaire.md, info/general.md, outils/ldap.md, outils/meta-doc.md, outils/sauvegardes.md, services/sql.md, services/web.md
Une case de cochée là dedans : https://forum.club1.fr/d/21
=> Ajout de définitions pour Debian, Linux et logiciel libre

glossaire.md, info/politique-de-vie-privee.md, outils/aliases.md
Je ne me rend pas compte si c'est clair ou si c'est plus perturbant qu'autre chose, mais comme les pages Wikipédia sont en train d'évoluer aussi dans cette direction (plutôt parler de POSIX que d'Unix), je me dit que c'est l'occasion.
=> POSIXification de la doc (ajout et utilisation de ce terme)

.github/requirements.txt
All our custom patches have been merged in this release.
=> Upgrade to latest Sphinx release

outils/forum.md
=> Ajout de deux extensions flarum maintenues par CLUB1

services/matrix.md
Sous la forme d'un bloc de code dans un premier temps pour plus de facilité.
Correspond à une bonne partie de : https://forum.club1.fr/d/110
=> Ajout des configurations spécifiques du serveur Synapse

services/matrix.md
En fait je me dit que c'est aussi sympa de faire des liens vers les pages en rapport avec ces choix.
=> Ajout de liens à explorer sur la configuration de Synapse

.github/workflows/build.yml, .github/workflows/clean.yml, .github/workflows/pages.yml
Permet de publier sur les pages GitHub le rendu HTML de chaque Pull Request, comme on peut en voir la démonstration avec le commentaire juste au dessous.
=> Add github action preview pr

services/matrix.md
Hitoire que ce soit plus digeste et en français, permet de fermer <https://forum.club1.fr/d/110>
=> Récapitulatif des configs Synapse avec des tableaux

tutos/webdav-android.md
- Remplacement des applis SimpleMobileTools par Fossify
- Utilisation du term 'logiciel libre' dans le tuto WebDAV Adnroid
=> tuto webdav android fossify

outils/compta.md
Ça va avec la mise à jour de https://github.com/club-1/compta 1.3 sur le serveur
=> ajoute compta-effectuer et un tips

faq.md, glossaire.md
+ complète le terme Nom de Domaine
C'est pas facile du tout à expliquer tout ça !
Au début j'ai tenté de rajouter un terme "sous-domaine", mais c'est méga galère et redondant avec NDD. Au final j'ai tenté d'utiliser plutôt les **niveaux de domaines**.
Par exemple sur Wikipedia, il n'y a pas d'entrée pour sous-domaine, mais il y en a pour TLD et SLD. Quand on tape sur google, il n'y a que des hébergeurs et des vendeurs de SEO qui utilisent ce terme.
=> faq : nouvelle entrée : nom de domaine externe

outils/site.md
+ explication du rôle éditeur, qui est le rôle par défaut
+ inversion entre création d'un page et éditon.
+ mise en avant du salon Matrix en haut de page. deux références à cet espace plus bas dans la page.
+ mise à jour de l'édition suite au passage aux pages V2
=> correction suite à la mise en place de LDAP pour le site Web

services/drive.md
+ sépare la petite histoire du logiciel dans un autre chapitre.
=> encart indiquant l'abscence des fichiers cachés sur le drive

info/general.md
Maintenant que l'on est sur Debian 12 !
=> MAJ des versions de logiciels

services/email.md
Remplacement de SPF policyd par OpenDMARC
=> email: MAJ config DMARC

services/matrix.md
Histoire de fermer ce ticket: https://forum.club1.fr/d/110-section-a-propos-des-configurations-specifiques-a-club1fr-du-serveur-synapse
=> matrix: ajout d'une configuration spéciale supplémentaire

tutos/premiere-connexion-ssh.md
- utilise le nouveau terme 'commande'
- ajoute le terme 'dossier caché' pour `~/.ssh`
- remplace <utilisateur> par UTILISATEUR
=> petite update du tuto premiere co ssh
